### ISSUE TITLE
Reintroduce deps: `com.softwaremill.sttp.client3::slf4j-backend`

### ISSUE THREAD

**Issue by nedsociety** [devsisters/shardcake#171]
A regression from #167.

```
java.lang.NoClassDefFoundError: sttp/client3/logging/slf4j/Slf4jLogger
```

zio-k8s still depends on sttp3, and its logging backend which is NOT a transitive dependency. It should be imported manually as described in zio-k8s documentation:

https://github.com/coralogix/zio-k8s/blob/16ef1c94944409dc955d5f8909b50f00c4df3a9d/docs/overview/gettingstarted.md?plain=1#L26-L28
